using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using AppAutomation.Abstractions;
using AppAutomation.Recorder.Avalonia.SourceScanning;
using Avalonia.Controls;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;

namespace AppAutomation.Recorder.Avalonia.CodeGeneration;

internal sealed class AuthoringCodeGenerator
{
    private const string RecorderGeneratedMarker = "// <auto-generated by AppAutomation Recorder />";
    private const string AutosaveDestinationMarkerPrefix = "// AppAutomation recorder autosave destination: ";
    private readonly AuthoringProjectScanner _scanner;
    private readonly ILogger? _logger;
    private readonly Dictionary<string, AutosaveTargetRegistration> _autosaveTargets = new(StringComparer.Ordinal);

    public AuthoringCodeGenerator(AuthoringProjectScanner scanner, ILogger? logger)
    {
        _scanner = scanner ?? throw new ArgumentNullException(nameof(scanner));
        _logger = logger;
    }

    public Task<RecorderSaveResult> SaveAsync(
        Window window,
        AppAutomationRecorderOptions options,
        IReadOnlyList<RecordedStep> steps,
        string? outputDirectoryOverride,
        CancellationToken cancellationToken = default)
    {
        return SaveCoreAsync(window, options, steps, outputDirectoryOverride, AuthoringSaveKind.Snapshot, saveContext: null, cancellationToken);
    }

    internal Task<RecorderSaveResult> SaveAsync(
        Window window,
        AppAutomationRecorderOptions options,
        IReadOnlyList<RecordedStep> steps,
        string? outputDirectoryOverride,
        RecorderScenarioSaveContext saveContext,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(saveContext);
        return SaveCoreAsync(window, options, steps, outputDirectoryOverride, AuthoringSaveKind.Snapshot, saveContext, cancellationToken);
    }

    public Task<RecorderSaveResult> AutosaveAsync(
        Window window,
        AppAutomationRecorderOptions options,
        IReadOnlyList<RecordedStep> steps,
        string? outputDirectoryOverride,
        CancellationToken cancellationToken = default)
    {
        return SaveCoreAsync(window, options, steps, outputDirectoryOverride, AuthoringSaveKind.Autosave, saveContext: null, cancellationToken);
    }

    internal Task<RecorderSaveResult> AutosaveAsync(
        Window window,
        AppAutomationRecorderOptions options,
        IReadOnlyList<RecordedStep> steps,
        string? outputDirectoryOverride,
        RecorderScenarioSaveContext saveContext,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(saveContext);
        return SaveCoreAsync(window, options, steps, outputDirectoryOverride, AuthoringSaveKind.Autosave, saveContext, cancellationToken);
    }

    private async Task<RecorderSaveResult> SaveCoreAsync(
        Window window,
        AppAutomationRecorderOptions options,
        IReadOnlyList<RecordedStep> steps,
        string? outputDirectoryOverride,
        AuthoringSaveKind saveKind,
        RecorderScenarioSaveContext? saveContext,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(window);
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(steps);

        if (steps.Count == 0)
        {
            return RecorderSaveResult.Failed("Recorder has no supported steps to save.");
        }

        if (string.IsNullOrWhiteSpace(options.AuthoringProjectDirectory))
        {
            return RecorderSaveResult.Failed("Authoring project directory is not configured.");
        }

        var projectDirectory = Path.GetFullPath(options.AuthoringProjectDirectory);
        if (!Directory.Exists(projectDirectory))
        {
            return RecorderSaveResult.Failed($"Authoring project directory '{projectDirectory}' does not exist.");
        }

        var target = ResolveTargetConfiguration(window, options, projectDirectory, outputDirectoryOverride, saveContext);
        var snapshot = _scanner.Scan(target, cancellationToken);
        var validationError = ValidateSnapshot(target, snapshot);
        if (validationError is not null)
        {
            return RecorderSaveResult.Failed(validationError);
        }

        var diagnostics = new List<string>();
        var activeSteps = steps.Where(static step => !step.IsIgnored).ToArray();
        var activeGraphValidation = RecorderScenarioGraphValidator.Validate(activeSteps);
        if (!activeGraphValidation.Success)
        {
            return RecorderSaveResult.Failed(
                $"Recorder checkpoint graph is invalid: {activeGraphValidation.Error}");
        }

        var persistableSteps = activeSteps.Where(static step => step.CanPersist).ToArray();
        var skippedSteps = activeSteps.Where(static step => !step.CanPersist).ToArray();
        foreach (var skippedStep in skippedSteps)
        {
            diagnostics.Add(
                string.IsNullOrWhiteSpace(skippedStep.ValidationMessage)
                    ? $"Skipped invalid step '{skippedStep.ActionKind}'."
                    : skippedStep.ValidationMessage!);
        }

        if (persistableSteps.Length == 0)
        {
            return RecorderSaveResult.Failed(
                "Recorder has no valid steps to save.",
                diagnostics.ToArray());
        }

        var invalidSemanticStep = skippedSteps.FirstOrDefault(static step =>
            step.ActionKind is RecordedActionKind.CaptureCheckpoint or RecordedActionKind.AssertValue);
        if (invalidSemanticStep is not null)
        {
            return RecorderSaveResult.Failed(
                invalidSemanticStep.ValidationMessage
                ?? $"Recorder checkpoint step '{invalidSemanticStep.ActionKind}' is invalid and must be fixed or removed before save.",
                diagnostics.ToArray());
        }

        var graphValidation = RecorderScenarioGraphValidator.Validate(persistableSteps);
        if (!graphValidation.Success)
        {
            return RecorderSaveResult.Failed(
                $"Recorder checkpoint graph is invalid: {graphValidation.Error}",
                diagnostics.ToArray());
        }

        var plannedControlsByKey = new Dictionary<string, RecordedControlDescriptor>(StringComparer.Ordinal);
        foreach (var stepGroup in persistableSteps.GroupBy(step =>
                     AuthoringProjectScanner.CreateControlKey(step.Control.LocatorKind, step.Control.LocatorValue)))
        {
            var typedSteps = stepGroup
                .Where(static step => !IsTypeAgnosticControlAction(step.ActionKind))
                .ToArray();
            var requiredTypes = typedSteps
                .Select(static step => step.Control.ControlType)
                .Distinct()
                .ToArray();
            if (requiredTypes.Length > 1)
            {
                var control = stepGroup.First().Control;
                return RecorderSaveResult.Failed(
                    $"Recorded actions for locator '{control.LocatorKind}:{control.LocatorValue}' require incompatible control types: {string.Join(", ", requiredTypes.Select(static type => $"UiControlType.{type}"))}. Recorder will not generate duplicate control properties.",
                    diagnostics.ToArray());
            }

            plannedControlsByKey.Add(
                stepGroup.Key,
                (typedSteps.FirstOrDefault() ?? stepGroup.First()).Control);
        }

        var reservedPropertyNames = new HashSet<string>(snapshot.ExistingControlPropertyNames, StringComparer.Ordinal);
        var generatedControlsByKey = new Dictionary<string, ExistingControlInfo>(StringComparer.Ordinal);
        var generatedControls = new List<ExistingControlInfo>();
        var renderedStatements = new List<string>(persistableSteps.Length);

        foreach (var step in persistableSteps)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var key = AuthoringProjectScanner.CreateControlKey(step.Control.LocatorKind, step.Control.LocatorValue);
            var typedKey = AuthoringProjectScanner.CreateTypedControlKey(
                step.Control.LocatorKind,
                step.Control.LocatorValue,
                step.Control.ControlType);
            var hasExistingControl = snapshot.ExistingControlsByKey.TryGetValue(key, out var existingControl);
            ExistingControlInfo? controlInfo = null;
            if (IsTypeAgnosticControlAction(step.ActionKind) && hasExistingControl)
            {
                controlInfo = existingControl;
            }
            else if (snapshot.ExistingControlsByTypedKey.TryGetValue(typedKey, out var existingTypedControl))
            {
                controlInfo = existingTypedControl;
            }
            else if (hasExistingControl)
            {
                return RecorderSaveResult.Failed(
                    CreateIncompatibleControlMessage(step, existingControl!),
                    diagnostics.ToArray());
            }
            else if (generatedControlsByKey.TryGetValue(key, out var generatedControl))
            {
                if (!IsTypeAgnosticControlAction(step.ActionKind)
                    && generatedControl.ControlType != step.Control.ControlType)
                {
                    return RecorderSaveResult.Failed(
                        CreateIncompatibleControlMessage(step, generatedControl),
                        diagnostics.ToArray());
                }

                controlInfo = generatedControl;
            }
            else
            {
                var plannedControl = plannedControlsByKey[key];
                var propertyName = RecorderNaming.EnsureUniqueName(plannedControl.ProposedPropertyName, reservedPropertyNames);
                controlInfo = new ExistingControlInfo(
                    propertyName,
                    plannedControl.ControlType,
                    plannedControl.LocatorValue,
                    plannedControl.LocatorKind,
                    plannedControl.FallbackToName);
                generatedControlsByKey.Add(key, controlInfo);
                generatedControls.Add(controlInfo);

                if (!string.Equals(propertyName, plannedControl.ProposedPropertyName, StringComparison.Ordinal))
                {
                    diagnostics.Add(
                        $"Control '{plannedControl.LocatorValue}' was renamed from '{plannedControl.ProposedPropertyName}' to '{propertyName}' to avoid a collision.");
                }
            }

            if (!string.IsNullOrWhiteSpace(step.Warning))
            {
                diagnostics.Add(step.Warning);
            }

            renderedStatements.Add(GenerateStepStatement(
                step,
                controlInfo!.PropertyName,
                graphValidation.CheckpointVariables));
        }

        var containsAssertions = persistableSteps.Any(
            static step => step.ActionKind == RecordedActionKind.AssertValue);
        var containsRelativeDates = persistableSteps.Any(HasRelativeDateExpression);

        Directory.CreateDirectory(target.OutputDirectory);
        var fileSafeScenarioName = RecorderNaming.CreateFileSafeName(target.ScenarioName, "scenario");
        var saveTarget = saveKind == AuthoringSaveKind.Autosave
            ? GetOrCreateAutosaveTarget(
                target,
                snapshot,
                fileSafeScenarioName,
                saveContext?.DraftIdentity,
                reservePageFile: saveContext is not null && generatedControls.Count > 0)
            : CreateSnapshotTarget(target, snapshot);
        IReadOnlyList<ExistingControlInfo> controlsToWrite;
        if (generatedControls.Count == 0)
        {
            controlsToWrite = Array.Empty<ExistingControlInfo>();
        }
        else if (!TryMergeControlsFile(
                     saveTarget.PageFilePath,
                     generatedControls,
                     cancellationToken,
                     out controlsToWrite,
                     out var controlsMergeError))
        {
            return RecorderSaveResult.Failed(controlsMergeError!, diagnostics.ToArray());
        }
        var pageFilePath = generatedControls.Count == 0
            ? null
            : saveTarget.PageFilePath;
        var scenarioFilePath = saveTarget.ScenarioFilePath;
        var autosaveDestinationId = saveKind == AuthoringSaveKind.Autosave
            ? CreateAutosaveDestinationId(target)
            : null;

        var pageSource = pageFilePath is null
            ? null
            : GeneratePagePartial(target, snapshot.PageClass!, controlsToWrite, autosaveDestinationId);
        string scenarioSource;
        if (saveKind == AuthoringSaveKind.Autosave || !File.Exists(scenarioFilePath))
        {
            scenarioSource = GenerateScenarioPartial(
                target,
                snapshot.ScenarioClass!,
                saveTarget.MethodName,
                renderedStatements,
                containsAssertions,
                containsRelativeDates,
                isAutosave: saveKind == AuthoringSaveKind.Autosave,
                autosaveDestinationId: autosaveDestinationId);
        }
        else if (!TryMergeScenarioPartial(
                     scenarioFilePath,
                     target,
                     snapshot.ScenarioClass!,
                     saveTarget.MethodName,
                     renderedStatements,
                     containsAssertions,
                     containsRelativeDates,
                     cancellationToken,
                     out var mergedScenarioSource,
                     out var scenarioMergeError))
        {
            return RecorderSaveResult.Failed(scenarioMergeError!, diagnostics.ToArray());
        }
        else
        {
            scenarioSource = mergedScenarioSource!;
        }

        if (pageFilePath is not null)
        {
            await File.WriteAllTextAsync(pageFilePath, pageSource!, cancellationToken);
        }

        await File.WriteAllTextAsync(scenarioFilePath, scenarioSource, cancellationToken);

        if (saveKind == AuthoringSaveKind.Snapshot)
        {
            CleanupAutosaveTargets(target, diagnostics);
        }

        _logger?.LogInformation(
            "Recorder saved scenario '{ScenarioName}' to '{ScenarioFilePath}' with {GeneratedControlCount} new controls.",
            target.ScenarioName,
            scenarioFilePath,
            generatedControls.Count);

        var saveVerb = saveKind == AuthoringSaveKind.Autosave ? "autosaved" : "saved";
        var message = skippedSteps.Length == 0
            ? $"Recorded scenario '{target.ScenarioName}' was {saveVerb}."
            : $"Recorded scenario '{target.ScenarioName}' was {saveVerb}. {skippedSteps.Length} invalid step(s) were skipped.";

        return RecorderSaveResult.Completed(
            message,
            pageFilePath,
            scenarioFilePath,
            persistedStepCount: persistableSteps.Length,
            skippedStepCount: skippedSteps.Length,
            diagnostics);
    }

    private static bool IsTypeAgnosticControlAction(RecordedActionKind actionKind)
    {
        return actionKind is RecordedActionKind.WaitUntilExists
            or RecordedActionKind.InvokeContextMenuItem;
    }

    private static string CreateIncompatibleControlMessage(
        RecordedStep step,
        ExistingControlInfo existingControl)
    {
        return $"Control '{existingControl.PropertyName}' for locator '{step.Control.LocatorKind}:{step.Control.LocatorValue}' is declared as UiControlType.{existingControl.ControlType}, which is incompatible with {step.ActionKind} requiring UiControlType.{step.Control.ControlType}. Recorder will not generate a duplicate control property.";
    }

    internal RecorderOutputDescription DescribeOutput(
        Window window,
        AppAutomationRecorderOptions options,
        string? outputDirectoryOverride,
        RecorderScenarioSaveContext? saveContext = null)
    {
        ArgumentNullException.ThrowIfNull(window);
        ArgumentNullException.ThrowIfNull(options);

        if (string.IsNullOrWhiteSpace(options.AuthoringProjectDirectory))
        {
            return new RecorderOutputDescription(
                IsConfigured: false,
                ScenarioFilePathDisplay: "Authoring project directory is not configured.",
                OutputDirectory: null,
                PageFilePathDisplay: null);
        }

        var projectDirectory = Path.GetFullPath(options.AuthoringProjectDirectory);
        var target = ResolveTargetConfiguration(window, options, projectDirectory, outputDirectoryOverride, saveContext);
        var scenarioFilePathDisplay = Path.Combine(
            target.OutputDirectory,
            $"{target.ScenarioClassName}.RecorderScenarios.g.cs");
        var pageFilePathDisplay = $"{target.PageClassName}.RecorderControls.g.cs (beside Page source)";

        return new RecorderOutputDescription(
            IsConfigured: true,
            ScenarioFilePathDisplay: scenarioFilePathDisplay,
            OutputDirectory: target.OutputDirectory,
            PageFilePathDisplay: pageFilePathDisplay);
    }

    public string GeneratePreview(IReadOnlyList<RecordedStep> steps)
    {
        ArgumentNullException.ThrowIfNull(steps);
        if (steps.Count == 0)
        {
            return string.Empty;
        }

        var graphValidation = RecorderScenarioGraphValidator.Validate(steps);
        if (!graphValidation.Success)
        {
            return $"// AppAutomation recorder checkpoint error: {SanitizeCommentText(graphValidation.Error ?? "Unknown checkpoint graph error.")}";
        }

        var builder = new StringBuilder();
        foreach (var step in steps)
        {
            builder.AppendLine(GenerateStepStatement(
                step,
                step.Control.ProposedPropertyName,
                graphValidation.CheckpointVariables));
        }

        return builder.ToString().TrimEnd();
    }

    public string GeneratePreview(RecordedStep step)
    {
        ArgumentNullException.ThrowIfNull(step);
        return GeneratePreview([step]);
    }

    internal string GeneratePreviewForStep(
        RecordedStep step,
        IReadOnlyList<RecordedStep> scenarioSteps)
    {
        ArgumentNullException.ThrowIfNull(step);
        ArgumentNullException.ThrowIfNull(scenarioSteps);
        var graphValidation = RecorderScenarioGraphValidator.Validate(scenarioSteps);
        if (graphValidation.StepErrors.TryGetValue(step.StepId, out var error))
        {
            return $"// AppAutomation recorder checkpoint error: {SanitizeCommentText(error)}";
        }

        var checkpointVariables = graphValidation.CheckpointVariables;
        if (step.ActionKind == RecordedActionKind.CaptureCheckpoint
            && step.CheckpointId is { } checkpointId
            && !checkpointVariables.ContainsKey(checkpointId))
        {
            var variables = new Dictionary<Guid, string>(checkpointVariables);
            var reservedNames = variables.Values.ToHashSet(StringComparer.Ordinal);
            variables[checkpointId] = RecorderNaming.CreateCheckpointVariableName(
                step.CheckpointVariableName,
                reservedNames);
            checkpointVariables = variables;
        }

        return GenerateStepStatement(
            step,
            step.Control.ProposedPropertyName,
            checkpointVariables);
    }

    private static string? ValidateSnapshot(AuthoringTargetConfiguration target, AuthoringProjectSnapshot snapshot)
    {
        if (snapshot.PageClass is null)
        {
            return $"Page class '{target.PageNamespace}.{target.PageClassName}' was not found in '{target.ProjectDirectory}'.";
        }

        if (!snapshot.PageClass.IsPartial)
        {
            return $"Page class '{target.PageNamespace}.{target.PageClassName}' must be partial for recorder-generated attributes.";
        }

        if (snapshot.ScenarioClass is null)
        {
            return $"Scenario class '{target.ScenarioNamespace}.{target.ScenarioClassName}' was not found in '{target.ProjectDirectory}'.";
        }

        if (!snapshot.ScenarioClass.IsPartial)
        {
            return $"Scenario class '{target.ScenarioNamespace}.{target.ScenarioClassName}' must be partial for recorder-generated methods.";
        }

        if (target.ScenarioGenericArity is not null
            && (snapshot.ScenarioClass.GenericArity != target.ScenarioGenericArity
                || !string.Equals(
                    snapshot.ScenarioClass.TypeParameterSignature,
                    target.ScenarioTypeParameterSignature,
                    StringComparison.Ordinal)))
        {
            return $"Scenario class '{target.ScenarioNamespace}.{target.ScenarioClassName}' no longer matches the selected generic declaration.";
        }

        return null;
    }

    private static AuthoringSaveTarget CreateSnapshotTarget(
        AuthoringTargetConfiguration target,
        AuthoringProjectSnapshot snapshot)
    {
        var reservedMethodNames = new HashSet<string>(snapshot.ExistingScenarioMethodNames, StringComparer.Ordinal);
        var timestamp = DateTimeOffset.Now;
        var methodName = RecorderNaming.EnsureUniqueName(
            RecorderNaming.CreateRecordedMethodBaseName(target.ScenarioName, timestamp),
            reservedMethodNames);
        var pageDirectory = Path.GetDirectoryName(snapshot.PageClass!.SourceFilePath)
            ?? throw new InvalidOperationException(
                $"Page source path '{snapshot.PageClass.SourceFilePath}' has no parent directory.");
        var pageFilePath = Path.Combine(pageDirectory, $"{target.PageClassName}.RecorderControls.g.cs");
        var scenarioFilePath = Path.Combine(
            target.OutputDirectory,
            $"{target.ScenarioClassName}.RecorderScenarios.g.cs");
        return new AuthoringSaveTarget(pageFilePath, scenarioFilePath, methodName);
    }

    private AuthoringSaveTarget GetOrCreateAutosaveTarget(
        AuthoringTargetConfiguration target,
        AuthoringProjectSnapshot snapshot,
        string fileSafeScenarioName,
        string? draftIdentity,
        bool reservePageFile)
    {
        var key = CreateAutosaveTargetKey(target, draftIdentity);
        if (_autosaveTargets.TryGetValue(key, out var existingRegistration))
        {
            return existingRegistration.Target;
        }

        var reservedMethodNames = new HashSet<string>(snapshot.ExistingScenarioMethodNames, StringComparer.Ordinal);
        var timestamp = DateTimeOffset.Now;
        var timestampText = timestamp.ToString("yyyyMMdd_HHmmss_fff", CultureInfo.InvariantCulture);
        var methodName = RecorderNaming.EnsureUniqueName(
            RecorderNaming.CreateAutosaveMethodBaseName(target.ScenarioName, timestamp),
            reservedMethodNames);
        for (var suffix = 1; ; suffix++)
        {
            var collisionSuffix = suffix == 1 ? string.Empty : $"_{suffix}";
            var pageFilePath = Path.Combine(
                target.OutputDirectory,
                $"{target.PageClassName}.{fileSafeScenarioName}.autosave.{timestampText}{collisionSuffix}.controls.g.cs.autosave");
            var scenarioFilePath = Path.Combine(
                target.OutputDirectory,
                $"{target.ScenarioClassName}.{fileSafeScenarioName}.autosave.{timestampText}{collisionSuffix}.g.cs.autosave");
            if (File.Exists(pageFilePath) || File.Exists(scenarioFilePath))
            {
                continue;
            }

            if (!TryReserveFile(scenarioFilePath))
            {
                continue;
            }

            if (reservePageFile && !TryReserveFile(pageFilePath))
            {
                TryDeleteReservedFile(scenarioFilePath);
                continue;
            }

            var collisionSafeMethodName = suffix == 1
                ? methodName
                : RecorderNaming.EnsureUniqueName($"{methodName}_{suffix}", reservedMethodNames);
            var autosaveTarget = new AuthoringSaveTarget(pageFilePath, scenarioFilePath, collisionSafeMethodName);
            _autosaveTargets.Add(
                key,
                new AutosaveTargetRegistration(
                    CreateAutosaveDestinationKey(target),
                    autosaveTarget));
            return autosaveTarget;
        }
    }

    private bool TryMergeControlsFile(
        string pageFilePath,
        IReadOnlyList<ExistingControlInfo> generatedControls,
        CancellationToken cancellationToken,
        out IReadOnlyList<ExistingControlInfo> mergedControls,
        out string? error)
    {
        if (File.Exists(pageFilePath))
        {
            string existingSource;
            try
            {
                existingSource = File.ReadAllText(pageFilePath);
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                mergedControls = Array.Empty<ExistingControlInfo>();
                error = $"Recorder controls file '{pageFilePath}' could not be read and was not changed: {exception.Message}";
                return false;
            }

            if (existingSource.Length > 0)
            {
                if (!existingSource.Contains(RecorderGeneratedMarker, StringComparison.Ordinal))
                {
                    mergedControls = Array.Empty<ExistingControlInfo>();
                    error = $"Recorder controls file '{pageFilePath}' is not owned by AppAutomation Recorder and was not changed.";
                    return false;
                }

                var syntaxTree = CSharpSyntaxTree.ParseText(existingSource, cancellationToken: cancellationToken);
                var syntaxError = syntaxTree.GetDiagnostics(cancellationToken)
                    .FirstOrDefault(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
                if (syntaxError is not null)
                {
                    mergedControls = Array.Empty<ExistingControlInfo>();
                    error = $"Recorder controls file '{pageFilePath}' contains invalid C# and was not changed: {syntaxError.GetMessage(CultureInfo.InvariantCulture)}";
                    return false;
                }
            }
        }

        var mergeByLocator = pageFilePath.EndsWith(".autosave", StringComparison.OrdinalIgnoreCase);
        var controlsByKey = new Dictionary<string, ExistingControlInfo>(StringComparer.Ordinal);
        foreach (var control in _scanner.ScanControlsFile(pageFilePath, cancellationToken))
        {
            controlsByKey.TryAdd(
                CreateControlsMergeKey(control, mergeByLocator),
                control);
        }

        foreach (var control in generatedControls)
        {
            controlsByKey[CreateControlsMergeKey(control, mergeByLocator)] = control;
        }

        mergedControls = controlsByKey.Values.ToArray();
        error = null;
        return true;
    }

    private static string CreateControlsMergeKey(ExistingControlInfo control, bool mergeByLocator)
        => mergeByLocator
            ? AuthoringProjectScanner.CreateControlKey(control.LocatorKind, control.LocatorValue)
            : AuthoringProjectScanner.CreateTypedControlKey(
                control.LocatorKind,
                control.LocatorValue,
                control.ControlType);

    internal static bool TryReserveFile(string filePath)
    {
        try
        {
            using var stream = new FileStream(filePath, FileMode.CreateNew, FileAccess.Write, FileShare.None);
            return true;
        }
        catch (IOException) when (File.Exists(filePath))
        {
            return false;
        }
    }

    private static void TryDeleteReservedFile(string filePath)
    {
        try
        {
            File.Delete(filePath);
        }
        catch (IOException)
        {
            // Best effort cleanup of a zero-length reservation created by this save attempt.
        }
        catch (UnauthorizedAccessException)
        {
            // Best effort cleanup of a zero-length reservation created by this save attempt.
        }
    }

    private static string CreateAutosaveTargetKey(AuthoringTargetConfiguration target, string? draftIdentity)
    {
        return string.Join(
            "\n",
            CreateAutosaveDestinationKey(target),
            target.ScenarioName,
            draftIdentity ?? string.Empty,
            target.OutputDirectory);
    }

    private static string CreateAutosaveDestinationKey(AuthoringTargetConfiguration target)
    {
        return string.Join(
            "\n",
            target.ProjectDirectory,
            target.AutosaveDirectory,
            target.PageNamespace,
            target.PageClassName,
            target.ScenarioNamespace,
            target.ScenarioClassName,
            target.ScenarioGenericArity?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            target.ScenarioTypeParameterSignature ?? string.Empty);
    }

    private static string CreateAutosaveDestinationId(AuthoringTargetConfiguration target)
    {
        var destinationKey = CreateAutosaveDestinationKey(target);
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(destinationKey)));
    }

    private void CleanupAutosaveTargets(
        AuthoringTargetConfiguration target,
        ICollection<string> diagnostics)
    {
        var destinationKey = CreateAutosaveDestinationKey(target);
        var attemptedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var matchingKeys = _autosaveTargets
            .Where(pair => string.Equals(pair.Value.DestinationKey, destinationKey, StringComparison.Ordinal))
            .Select(static pair => pair.Key)
            .ToArray();

        foreach (var key in matchingKeys)
        {
            var targetToDelete = _autosaveTargets[key].Target;
            attemptedPaths.Add(targetToDelete.PageFilePath);
            attemptedPaths.Add(targetToDelete.ScenarioFilePath);
            var pageDeleted = TryDeleteAutosaveFile(targetToDelete.PageFilePath, diagnostics);
            var scenarioDeleted = TryDeleteAutosaveFile(targetToDelete.ScenarioFilePath, diagnostics);
            if (pageDeleted && scenarioDeleted)
            {
                _autosaveTargets.Remove(key);
            }
        }

        foreach (var filePath in FindAutosaveFilesForDestination(target, diagnostics))
        {
            if (attemptedPaths.Add(filePath))
            {
                TryDeleteAutosaveFile(filePath, diagnostics);
            }
        }
    }

    private static List<string> FindAutosaveFilesForDestination(
        AuthoringTargetConfiguration target,
        ICollection<string> diagnostics)
    {
        var destinationId = CreateAutosaveDestinationId(target);
        var files = new List<string>();

        foreach (var directory in new[] { target.AutosaveDirectory, target.OutputDirectory }
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            if (!Directory.Exists(directory))
            {
                continue;
            }

            try
            {
                foreach (var filePath in Directory.EnumerateFiles(directory, "*.autosave", SearchOption.TopDirectoryOnly))
                {
                    if (string.Equals(
                            ReadAutosaveDestinationId(filePath, diagnostics),
                            destinationId,
                            StringComparison.Ordinal))
                    {
                        files.Add(filePath);
                    }
                }
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                diagnostics.Add(
                    $"Recorder saved the final scenario but could not inspect autosave recovery directory '{directory}': {exception.Message}");
            }
        }

        // Drafts produced before destination markers were introduced are removed once by the legacy name convention.
        files.AddRange(FindLegacyAutosaveFilesForDestination(target, diagnostics));
        return files.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
    }

    private static string? ReadAutosaveDestinationId(
        string filePath,
        ICollection<string> diagnostics)
    {
        try
        {
            var markerLine = File.ReadLines(filePath)
                .Take(4)
                .FirstOrDefault(line => line.StartsWith(
                    AutosaveDestinationMarkerPrefix,
                    StringComparison.Ordinal));
            return markerLine?[AutosaveDestinationMarkerPrefix.Length..];
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            diagnostics.Add(
                $"Recorder saved the final scenario but could not inspect autosave recovery file '{filePath}': {exception.Message}");
            return null;
        }
    }

    private static List<string> FindLegacyAutosaveFilesForDestination(
        AuthoringTargetConfiguration target,
        ICollection<string> diagnostics)
    {
        var destinationScenarioPrefix = $"{target.ScenarioClassName}.";
        var files = new List<string>();

        foreach (var directory in new[] { target.AutosaveDirectory, target.OutputDirectory }
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            if (!Directory.Exists(directory))
            {
                continue;
            }

            try
            {
                var autosaveFiles = Directory
                    .EnumerateFiles(directory, "*.autosave", SearchOption.TopDirectoryOnly)
                    .ToArray();
                foreach (var scenarioFilePath in autosaveFiles.Where(filePath =>
                             ReadAutosaveDestinationId(filePath, diagnostics) is null
                             && IsDestinationScenarioAutosave(Path.GetFileName(filePath), destinationScenarioPrefix)))
                {
                    files.Add(scenarioFilePath);
                    var pairedPageFilePath = GetPairedPageAutosavePath(
                        target.PageClassName,
                        scenarioFilePath,
                        destinationScenarioPrefix);
                    if (pairedPageFilePath is not null && File.Exists(pairedPageFilePath))
                    {
                        files.Add(pairedPageFilePath);
                    }
                }
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                diagnostics.Add(
                    $"Recorder saved the final scenario but could not inspect autosave recovery directory '{directory}': {exception.Message}");
            }
        }

        return files;
    }

    private static bool IsDestinationScenarioAutosave(
        string fileName,
        string scenarioPrefix)
    {
        return fileName.StartsWith(scenarioPrefix, StringComparison.OrdinalIgnoreCase)
            && fileName.EndsWith(".g.cs.autosave", StringComparison.OrdinalIgnoreCase);
    }

    private static string? GetPairedPageAutosavePath(
        string pageClassName,
        string scenarioFilePath,
        string scenarioPrefix)
    {
        const string scenarioSuffix = ".g.cs.autosave";
        var scenarioFileName = Path.GetFileName(scenarioFilePath);
        if (!IsDestinationScenarioAutosave(scenarioFileName, scenarioPrefix))
        {
            return null;
        }

        var recoveryIdentityLength = scenarioFileName.Length - scenarioPrefix.Length - scenarioSuffix.Length;
        if (recoveryIdentityLength <= 0)
        {
            return null;
        }

        var recoveryIdentity = scenarioFileName.Substring(scenarioPrefix.Length, recoveryIdentityLength);
        var directory = Path.GetDirectoryName(scenarioFilePath);
        return directory is null
            ? null
            : Path.Combine(directory, $"{pageClassName}.{recoveryIdentity}.controls.g.cs.autosave");
    }

    private static bool TryDeleteAutosaveFile(string filePath, ICollection<string> diagnostics)
    {
        try
        {
            File.Delete(filePath);
            return true;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            diagnostics.Add($"Recorder saved the final scenario but could not delete autosave recovery file '{filePath}': {exception.Message}");
            return false;
        }
    }

    private static AuthoringTargetConfiguration ResolveTargetConfiguration(
        Window window,
        AppAutomationRecorderOptions options,
        string projectDirectory,
        string? outputDirectoryOverride,
        RecorderScenarioSaveContext? saveContext)
    {
        var entryAssembly = Assembly.GetEntryAssembly();
        var appName = entryAssembly?.GetName().Name
            ?? window.GetType().Assembly.GetName().Name
            ?? "App";

        var pageClassName = options.PageClassName ?? $"{window.GetType().Name}Page";
        var destination = saveContext?.Destination;
        var scenarioClassName = destination?.ScenarioClassName
            ?? options.ScenarioClassName
            ?? $"{window.GetType().Name}ScenariosBase";
        var pageNamespace = options.PageNamespace ?? $"{appName}.UiTests.Authoring.Pages";
        var scenarioNamespace = destination?.ScenarioNamespace
            ?? options.ScenarioNamespace
            ?? $"{appName}.UiTests.Authoring.Tests";
        var outputSubdirectory = destination?.OutputSubdirectory ?? options.OutputSubdirectory;
        var autosaveDirectory = Path.IsPathRooted(outputSubdirectory)
            ? Path.GetFullPath(outputSubdirectory)
            : Path.Combine(projectDirectory, outputSubdirectory);
        var outputDirectory = string.IsNullOrWhiteSpace(outputDirectoryOverride)
            ? autosaveDirectory
            : Path.GetFullPath(outputDirectoryOverride);

        return new AuthoringTargetConfiguration(
            projectDirectory,
            outputDirectory,
            autosaveDirectory,
            pageNamespace,
            pageClassName,
            scenarioNamespace,
            scenarioClassName,
            destination?.GenericArity,
            destination?.TypeParameterSignature,
            saveContext?.ScenarioName ?? options.ScenarioName,
            appName);
    }

    private static string GeneratePagePartial(
        AuthoringTargetConfiguration target,
        ScannedClassInfo pageClass,
        IReadOnlyList<ExistingControlInfo> controls,
        string? autosaveDestinationId)
    {
        var builder = new StringBuilder();
        builder.AppendLine(RecorderGeneratedMarker);
        AppendAutosaveDestinationMarker(builder, autosaveDestinationId);
        builder.AppendLine("using AppAutomation.Abstractions;");
        builder.AppendLine();
        builder.Append("namespace ").Append(target.PageNamespace).AppendLine(";");
        builder.AppendLine();

        foreach (var control in controls)
        {
            builder.AppendLine(GenerateUiControlAttribute(control));
        }

        builder.Append(pageClass.ModifiersText)
            .Append(" partial class ")
            .Append(target.PageClassName)
            .AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool TryMergeScenarioPartial(
        string scenarioFilePath,
        AuthoringTargetConfiguration target,
        ScannedClassInfo scenarioClass,
        string methodName,
        IReadOnlyList<string> renderedStatements,
        bool containsAssertions,
        bool containsRelativeDates,
        CancellationToken cancellationToken,
        out string? mergedSource,
        out string? error)
    {
        cancellationToken.ThrowIfCancellationRequested();
        string existingSource;
        try
        {
            existingSource = File.ReadAllText(scenarioFilePath);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            mergedSource = null;
            error = $"Recorder scenario file '{scenarioFilePath}' could not be read and was not changed: {exception.Message}";
            return false;
        }

        if (!existingSource.Contains(RecorderGeneratedMarker, StringComparison.Ordinal))
        {
            mergedSource = null;
            error = $"Recorder scenario file '{scenarioFilePath}' is not owned by AppAutomation Recorder and was not changed.";
            return false;
        }

        var syntaxTree = CSharpSyntaxTree.ParseText(existingSource, cancellationToken: cancellationToken);
        var syntaxErrors = syntaxTree.GetDiagnostics(cancellationToken)
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        if (syntaxErrors.Length > 0)
        {
            mergedSource = null;
            error = $"Recorder scenario file '{scenarioFilePath}' contains invalid C# and was not changed: {syntaxErrors[0].GetMessage(CultureInfo.InvariantCulture)}";
            return false;
        }

        var root = syntaxTree.GetCompilationUnitRoot(cancellationToken);
        var matchingClasses = root.DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .Where(declaration => declaration.Ancestors().OfType<TypeDeclarationSyntax>().Any() == false
                && string.Equals(GetNamespaceName(declaration), target.ScenarioNamespace, StringComparison.Ordinal)
                && string.Equals(declaration.Identifier.ValueText, target.ScenarioClassName, StringComparison.Ordinal))
            .ToArray();
        if (matchingClasses.Length != 1)
        {
            mergedSource = null;
            error = $"Recorder scenario file '{scenarioFilePath}' does not contain exactly one expected class '{target.ScenarioNamespace}.{target.ScenarioClassName}' and was not changed.";
            return false;
        }

        var existingClass = matchingClasses[0];
        var genericArity = existingClass.TypeParameterList?.Parameters.Count ?? 0;
        var typeParameterSignature = CreateTypeParameterSignature(existingClass);
        if (!existingClass.Modifiers.Any(static token => token.IsKind(SyntaxKind.PartialKeyword))
            || genericArity != scenarioClass.GenericArity
            || !string.Equals(typeParameterSignature, scenarioClass.TypeParameterSignature, StringComparison.Ordinal)
            || existingClass.OpenBraceToken.IsMissing
            || existingClass.CloseBraceToken.IsMissing)
        {
            mergedSource = null;
            error = $"Recorder scenario file '{scenarioFilePath}' has an incompatible partial class declaration and was not changed.";
            return false;
        }

        var generatedSource = GenerateScenarioPartial(
            target,
            scenarioClass,
            methodName,
            renderedStatements,
            containsAssertions,
            containsRelativeDates,
            isAutosave: false,
            autosaveDestinationId: null);
        var generatedMethod = CSharpSyntaxTree.ParseText(generatedSource)
            .GetCompilationUnitRoot()
            .DescendantNodes()
            .OfType<MethodDeclarationSyntax>()
            .Single();
        var updatedClass = existingClass.AddMembers(generatedMethod);
        var updatedRoot = root.ReplaceNode(existingClass, updatedClass);
        if (containsRelativeDates && !HasUsingDirective(updatedRoot, "System"))
        {
            updatedRoot = updatedRoot.AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")));
        }

        mergedSource = updatedRoot
            .NormalizeWhitespace(indentation: "    ", eol: Environment.NewLine)
            .ToFullString() + Environment.NewLine;
        error = null;
        return true;
    }

    private static string GenerateScenarioPartial(
        AuthoringTargetConfiguration target,
        ScannedClassInfo scenarioClass,
        string methodName,
        IReadOnlyList<string> renderedStatements,
        bool containsAssertions,
        bool containsRelativeDates,
        bool isAutosave,
        string? autosaveDestinationId)
    {
        var builder = new StringBuilder();
        builder.AppendLine(RecorderGeneratedMarker);
        AppendAutosaveDestinationMarker(builder, autosaveDestinationId);
        builder.AppendLine("using AppAutomation.Abstractions;");
        if (containsRelativeDates)
        {
            builder.AppendLine("using System;");
        }

        builder.AppendLine("using TUnit.Core;");
        builder.AppendLine();
        builder.Append("namespace ").Append(target.ScenarioNamespace).AppendLine(";");
        builder.AppendLine();
        if (isAutosave)
        {
            builder.AppendLine("// AppAutomation recorder autosave recovery file.");
            builder.AppendLine("// This file is overwritten while the recorder session is running.");
            builder.AppendLine();
        }

        builder.Append(scenarioClass.ModifiersText)
            .Append(" partial class ")
            .Append(target.ScenarioClassName)
            .Append(scenarioClass.TypeParameterListText)
            .AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    [Test]");
        builder.AppendLine("    [NotInParallel(DesktopUiConstraint)]");
        builder.Append("    public ");
        if (containsAssertions)
        {
            builder.Append("async global::System.Threading.Tasks.Task ");
        }
        else
        {
            builder.Append("void ");
        }

        builder.Append(methodName).AppendLine("()");
        builder.AppendLine("    {");
        foreach (var statement in renderedStatements)
        {
            AppendIndentedBlock(builder, statement, "        ");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool HasUsingDirective(CompilationUnitSyntax root, string namespaceName)
    {
        return root.Usings.Any(usingDirective =>
            usingDirective.Alias is null
            && usingDirective.StaticKeyword.IsKind(SyntaxKind.None)
            && string.Equals(usingDirective.Name?.ToString(), namespaceName, StringComparison.Ordinal));
    }

    private static void AppendAutosaveDestinationMarker(StringBuilder builder, string? autosaveDestinationId)
    {
        if (!string.IsNullOrWhiteSpace(autosaveDestinationId))
        {
            builder.Append(AutosaveDestinationMarkerPrefix).AppendLine(autosaveDestinationId);
        }
    }

    private static string GetNamespaceName(SyntaxNode node)
    {
        return string.Join(
            ".",
            node.Ancestors()
                .OfType<BaseNamespaceDeclarationSyntax>()
                .Reverse()
                .Select(static declaration => declaration.Name.ToString()));
    }

    private static string CreateTypeParameterSignature(ClassDeclarationSyntax declaration)
    {
        return string.Join(
            ",",
            declaration.TypeParameterList?.Parameters
                .Select(static parameter => parameter.Identifier.ValueText)
                ?? Array.Empty<string>());
    }

    private static string GenerateUiControlAttribute(ExistingControlInfo control)
    {
        var builder = new StringBuilder();
        builder.Append("[UiControl(\"")
            .Append(EscapeString(control.PropertyName))
            .Append("\", UiControlType.")
            .Append(control.ControlType)
            .Append(", \"")
            .Append(EscapeString(control.LocatorValue))
            .Append("\"");

        if (control.LocatorKind != UiLocatorKind.AutomationId)
        {
            builder.Append(", LocatorKind = UiLocatorKind.")
                .Append(control.LocatorKind);
        }

        builder.Append(", FallbackToName = ")
            .Append(control.FallbackToName ? "true" : "false")
            .Append(")]");
        return builder.ToString();
    }

    private static string GenerateStepStatement(
        RecordedStep step,
        string propertyName,
        IReadOnlyDictionary<Guid, string> checkpointVariables)
    {
        var statement = step.ActionKind switch
        {
            RecordedActionKind.CaptureCheckpoint => GenerateCheckpointStatement(
                step,
                propertyName,
                checkpointVariables),
            RecordedActionKind.AssertValue => GenerateAssertionStatement(
                step,
                propertyName,
                checkpointVariables),
            RecordedActionKind.EnterText => $"Page.EnterText(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.ClickButton => $"Page.ClickButton(static page => page.{propertyName});",
            RecordedActionKind.SetChecked => $"Page.SetChecked(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.SetToggled => $"Page.SetToggled(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.SelectComboItem => $"Page.SelectComboItem(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.SelectListBoxItem => $"Page.SelectListBoxItem(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.SetSliderValue => $"Page.SetSliderValue(static page => page.{propertyName}, {FormatDouble(step.DoubleValue)});",
            RecordedActionKind.SetSpinnerValue => $"Page.SetSpinnerValue(static page => page.{propertyName}, {FormatDouble(step.DoubleValue)});",
            RecordedActionKind.SelectTabItem => $"Page.SelectTabItem(static page => page.{propertyName});",
            RecordedActionKind.SelectTreeItem => $"Page.SelectTreeItem(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.SetDate => $"Page.SetDate(static page => page.{propertyName}, {FormatDate(step.DateValue, step.DateExpression)});",
            RecordedActionKind.SetTime => $"Page.SetTime(static page => page.{propertyName}, {FormatTimeSpan(step.TimeValue)});",
            RecordedActionKind.SetExpanded => $"Page.SetExpanded(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.SetColor => $"Page.SetColor(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.WaitUntilTextEquals => $"Page.WaitUntilTextEquals(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.WaitUntilTextContains => $"Page.WaitUntilTextContains(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.WaitUntilValueEquals => $"Page.WaitUntilValueEquals(static page => page.{propertyName}, {FormatDouble(step.DoubleValue)});",
            RecordedActionKind.WaitUntilTimeEquals => $"Page.WaitUntilTimeEquals(static page => page.{propertyName}, {FormatTimeSpan(step.TimeValue)});",
            RecordedActionKind.WaitUntilIsExpanded => $"Page.WaitUntilIsExpanded(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.WaitUntilColorEquals => $"Page.WaitUntilColorEquals(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.InvokeMenuItem when step.Control.ControlType == UiControlType.Menu =>
                $"Page.InvokeMenuItem(static page => page.{propertyName}, {FormatOrderedStringValues(step.StringValues)});",
            RecordedActionKind.InvokeMenuItem => $"Page.InvokeMenuItem(static page => page.{propertyName});",
            RecordedActionKind.InvokeContextMenuItem =>
                $"Page.InvokeContextMenuItem(static page => page.{propertyName}, {FormatOrderedStringValues(step.StringValues)});",
            RecordedActionKind.WaitUntilIsChecked => $"Page.WaitUntilIsChecked(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.WaitUntilIsToggled => $"Page.WaitUntilIsToggled(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.WaitUntilIsSelected => $"Page.WaitUntilIsSelected(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.WaitUntilIsEnabled => $"Page.WaitUntilIsEnabled(static page => page.{propertyName}, {FormatBoolean(step.BoolValue)});",
            RecordedActionKind.WaitUntilExists => $"Page.WaitUntilExists(static page => page.{propertyName});",
            RecordedActionKind.WaitUntilGridRowsAtLeast => $"Page.WaitUntilGridRowsAtLeast(static page => page.{propertyName}, {FormatInt(step.IntValue)});",
            RecordedActionKind.WaitUntilGridContainsRow => $"Page.WaitUntilGridContainsRow(static page => page.{propertyName}, {FormatGridRowSelector(step)});",
            RecordedActionKind.WaitUntilGridCellEquals => HasNamedGridRow(step)
                ? $"Page.WaitUntilGridCellEquals(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, \"{EscapeString(step.StringValue ?? string.Empty)}\");"
                : $"Page.WaitUntilGridCellEquals(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.WaitUntilProgressAtLeast => $"Page.WaitUntilProgressAtLeast(static page => page.{propertyName}, {FormatDouble(step.DoubleValue)});",
            RecordedActionKind.WaitUntilListBoxContains => $"Page.WaitUntilListBoxContains(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.WaitUntilHasItemsAtLeast => $"Page.WaitUntilHasItemsAtLeast(static page => page.{propertyName}, {FormatInt(step.IntValue)});",
            RecordedActionKind.WaitUntilNotificationContains => $"Page.WaitUntilNotificationContains(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.SearchAndSelect => $"Page.SearchAndSelect(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\", \"{EscapeString(step.ItemValue ?? string.Empty)}\");",
            RecordedActionKind.SearchAndSelectGridCell => HasNamedGridRow(step)
                ? $"Page.SearchAndSelectGridCell(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, \"{EscapeString(step.StringValue ?? string.Empty)}\", \"{EscapeString(step.ItemValue ?? string.Empty)}\");"
                : $"Page.SearchAndSelectGridCell(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, \"{EscapeString(step.StringValue ?? string.Empty)}\", \"{EscapeString(step.ItemValue ?? string.Empty)}\");",
            RecordedActionKind.OpenGridRow => HasNamedGridRow(step)
                ? $"Page.OpenGridRow(static page => page.{propertyName}, {FormatGridRowSelector(step)});"
                : $"Page.OpenGridRow(static page => page.{propertyName}, {FormatInt(step.RowIndex)});",
            RecordedActionKind.SortGridByColumn => $"Page.SortGridByColumn(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.ScrollGridToEnd => $"Page.ScrollGridToEnd(static page => page.{propertyName});",
            RecordedActionKind.CopyGridCell => HasNamedGridRow(step)
                ? $"Page.CopyGridCell(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)});"
                : $"Page.CopyGridCell(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)});",
            RecordedActionKind.ExportGrid => $"Page.ExportGrid(static page => page.{propertyName});",
            RecordedActionKind.SetDateRangeFilter => $"Page.SetDateRangeFilter(static page => page.{propertyName}, {FormatNullableDate(step.DateValue, step.DateExpression)}, {FormatNullableDate(step.SecondDateValue, step.SecondDateExpression)}{FormatOptionalFilterCommitMode(step.FilterCommitMode)});",
            RecordedActionKind.SetNumericRangeFilter => $"Page.SetNumericRangeFilter(static page => page.{propertyName}, {FormatNullableDouble(step.DoubleValue)}, {FormatNullableDouble(step.SecondDoubleValue)}{FormatOptionalFilterCommitMode(step.FilterCommitMode)});",
            RecordedActionKind.SelectExportFolder => $"Page.SelectExportFolder(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalFolderExportCommitMode(step.FolderExportCommitMode)});",
            RecordedActionKind.EditGridCellText => HasNamedGridRow(step)
                ? $"Page.EditGridCellText(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.EditGridCellText(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.EditGridCellNumber => HasNamedGridRow(step)
                ? $"Page.EditGridCellNumber(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, {FormatDouble(step.DoubleValue)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.EditGridCellNumber(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, {FormatDouble(step.DoubleValue)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.EditGridCellDate => HasNamedGridRow(step)
                ? $"Page.EditGridCellDate(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, {FormatDate(step.DateValue, step.DateExpression)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.EditGridCellDate(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, {FormatDate(step.DateValue, step.DateExpression)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.EditGridCellTime => HasNamedGridRow(step)
                ? $"Page.EditGridCellTime(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, {FormatTimeSpan(step.TimeValue)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.EditGridCellTime(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, {FormatTimeSpan(step.TimeValue)}{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.EditGridCellColor => HasNamedGridRow(step)
                ? $"Page.EditGridCellColor(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.EditGridCellColor(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.SelectGridCellComboItem => HasNamedGridRow(step)
                ? $"Page.SelectGridCellComboItem(static page => page.{propertyName}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});"
                : $"Page.SelectGridCellComboItem(static page => page.{propertyName}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)}, \"{EscapeString(step.StringValue ?? string.Empty)}\"{FormatOptionalGridCellEditCommitMode(step.GridCellEditCommitMode)});",
            RecordedActionKind.ConfirmDialog => $"Page.ConfirmDialog(static page => page.{propertyName}{FormatOptionalStringArgument(step.StringValue)});",
            RecordedActionKind.CancelDialog => $"Page.CancelDialog(static page => page.{propertyName}{FormatOptionalStringArgument(step.StringValue)});",
            RecordedActionKind.DismissDialog => $"Page.DismissDialog(static page => page.{propertyName}{FormatOptionalStringArgument(step.StringValue)});",
            RecordedActionKind.DismissNotification => $"Page.DismissNotification(static page => page.{propertyName});",
            RecordedActionKind.OpenOrActivateShellPane => $"Page.OpenOrActivateShellPane(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.ActivateShellPane => $"Page.ActivateShellPane(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.SelectMultiItems => $"Page.SelectMultiItems(static page => page.{propertyName}, {FormatStringValues(step.StringValues)});",
            RecordedActionKind.CancelMultiSelection => $"Page.CancelMultiSelection(static page => page.{propertyName}, {FormatStringValues(step.StringValues)});",
            RecordedActionKind.ApplyFilterSelection => $"Page.ApplyFilterSelection(static page => page.{propertyName}, {FormatStringValues(step.StringValues)});",
            RecordedActionKind.CancelFilterSelection => $"Page.CancelFilterSelection(static page => page.{propertyName}, {FormatStringValues(step.StringValues)});",
            RecordedActionKind.EnterSearch => $"Page.EnterSearch(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            RecordedActionKind.ClearSearch => $"Page.ClearSearch(static page => page.{propertyName});",
            RecordedActionKind.ApplySearchFromHistory => $"Page.ApplySearchFromHistory(static page => page.{propertyName}, \"{EscapeString(step.StringValue ?? string.Empty)}\");",
            _ => $"// Unsupported recorded action '{step.ActionKind}'."
        };

        var commentParts = new List<string>();
        if (!string.IsNullOrWhiteSpace(step.Warning))
        {
            commentParts.Add(step.Warning!);
        }

        if (!string.IsNullOrWhiteSpace(step.ValidationMessage)
            && !commentParts.Contains(step.ValidationMessage!, StringComparer.Ordinal))
        {
            commentParts.Add(step.ValidationMessage!);
        }

        if (commentParts.Count > 0)
        {
            statement = $"{statement} // {string.Join(" | ", commentParts.Select(SanitizeCommentText))}";
        }

        var runtimeCommentLines = CreateRuntimeCommentLines(step);
        return runtimeCommentLines.Count == 0
            ? statement
            : string.Join(Environment.NewLine, runtimeCommentLines.Concat([statement]));
    }

    private static string GenerateCheckpointStatement(
        RecordedStep step,
        string propertyName,
        IReadOnlyDictionary<Guid, string> checkpointVariables)
    {
        var checkpointId = step.CheckpointId
            ?? throw new InvalidOperationException("Checkpoint step does not contain an id.");
        if (!checkpointVariables.TryGetValue(checkpointId, out var variableName))
        {
            throw new InvalidOperationException($"Checkpoint '{checkpointId}' was not validated.");
        }

        var expression = GenerateValueExpression(step, propertyName);
        if (step.ValueKind == RecorderValueKind.StringSet)
        {
            expression = $"global::System.Linq.Enumerable.ToArray({expression})";
        }

        return $"var {variableName} = {expression};";
    }

    private static string GenerateAssertionStatement(
        RecordedStep step,
        string propertyName,
        IReadOnlyDictionary<Guid, string> checkpointVariables)
    {
        var actual = GenerateValueExpression(step, propertyName);
        string expected;
        if (step.ExpectedCheckpointId is { } checkpointId)
        {
            if (!checkpointVariables.TryGetValue(checkpointId, out expected!))
            {
                throw new InvalidOperationException($"Assertion references unvalidated checkpoint '{checkpointId}'.");
            }
        }
        else
        {
            expected = FormatExpectedLiteral(step);
        }

        var assertion = step.ComparisonKind switch
        {
            RecorderComparisonKind.Equal =>
                $"global::TUnit.Assertions.Extensions.EqualsAssertionExtensions.IsEqualTo(global::TUnit.Assertions.Assert.That({actual}), {expected})",
            RecorderComparisonKind.Contains =>
                $"global::TUnit.Assertions.Extensions.StringContainsAssertionExtensions.Contains(global::TUnit.Assertions.Assert.That({actual}), {expected})",
            RecorderComparisonKind.Equivalent =>
                $"global::TUnit.Assertions.Extensions.IsEquivalentToAssertionExtensions.IsEquivalentTo(global::TUnit.Assertions.Assert.That({actual}), {expected})",
            _ => throw new InvalidOperationException("Assertion step does not contain a supported comparison.")
        };

        return $"await {assertion};";
    }

    private static string GenerateValueExpression(RecordedStep step, string propertyName)
    {
        var control = $"Page.{propertyName}";
        return step.ValueAccessorKind switch
        {
            RecorderValueAccessorKind.Text => $"{control}.Text",
            RecorderValueAccessorKind.SelectedItemText when step.Control.ControlType == UiControlType.SearchPicker =>
                $"{control}.SelectedItemText",
            RecorderValueAccessorKind.SelectedItemText when step.Control.ControlType == UiControlType.ListBox =>
                $"((global::AppAutomation.Abstractions.ISelectableListBoxControl){control}).SelectedItemText",
            RecorderValueAccessorKind.SelectedItemText => $"{control}.SelectedItem?.Text",
            RecorderValueAccessorKind.SelectedItems => $"{control}.SelectedItems",
            RecorderValueAccessorKind.NumericValue => $"{control}.Value",
            RecorderValueAccessorKind.SelectedDate => $"{control}.SelectedDate",
            RecorderValueAccessorKind.SelectedTime => $"{control}.SelectedTime",
            RecorderValueAccessorKind.Color => $"{control}.Color",
            RecorderValueAccessorKind.IsChecked => $"{control}.IsChecked",
            RecorderValueAccessorKind.IsToggled => $"{control}.IsToggled",
            RecorderValueAccessorKind.IsSelected when step.Control.ControlType == UiControlType.RadioButton =>
                $"{control}.IsChecked",
            RecorderValueAccessorKind.IsSelected => $"{control}.IsSelected",
            RecorderValueAccessorKind.IsExpanded => $"{control}.IsExpanded",
            RecorderValueAccessorKind.IsEnabled => $"{control}.IsEnabled",
            RecorderValueAccessorKind.GridCellText => GenerateGridCellExpression(step, control),
            _ => throw new InvalidOperationException(
                $"Value accessor '{step.ValueAccessorKind}' is not supported for {step.Control.ControlType}.")
        };
    }

    private static string GenerateGridCellExpression(RecordedStep step, string control)
    {
        return HasNamedGridRow(step)
            ? $"global::AppAutomation.Abstractions.GridValueReader.ReadCellText({control}, {FormatGridRowSelector(step)}, {FormatGridTargetColumn(step)})"
            : $"global::AppAutomation.Abstractions.GridValueReader.ReadCellText({control}, {FormatInt(step.RowIndex)}, {FormatInt(step.ColumnIndex)})";
    }

    private static string FormatExpectedLiteral(RecordedStep step)
    {
        return step.ValueKind switch
        {
            RecorderValueKind.Text or RecorderValueKind.Color or RecorderValueKind.GridCellText =>
                $"\"{EscapeString(step.StringValue ?? string.Empty)}\"",
            RecorderValueKind.Number => FormatDouble(step.DoubleValue),
            RecorderValueKind.Boolean => FormatBoolean(step.BoolValue),
            RecorderValueKind.Date => FormatNullableDate(step.DateValue, step.DateExpression),
            RecorderValueKind.Time => FormatNullableTimeSpan(step.TimeValue),
            RecorderValueKind.StringSet => FormatStringValues(step.StringValues),
            _ => throw new InvalidOperationException($"Literal value kind '{step.ValueKind}' is not supported.")
        };
    }

    private static void AppendIndentedBlock(StringBuilder builder, string block, string indent)
    {
        var normalized = block.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        foreach (var line in normalized.Split('\n'))
        {
            builder.Append(indent).AppendLine(line);
        }
    }

    private static IReadOnlyList<string> CreateRuntimeCommentLines(RecordedStep step)
    {
        var findings = step.RuntimeValidationFindings ?? Array.Empty<RecorderRuntimeValidationFinding>();
        return findings
            .Where(static finding => finding.ShouldSurface)
            .Select(static finding =>
            {
                var targetState = finding.BlocksTarget ? "unsupported" : "warning";
                return $"// AppAutomation recorder warning: {finding.Target} target {targetState} ({finding.Code}): {SanitizeCommentText(finding.Message)}";
            })
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    private static string SanitizeCommentText(string value)
    {
        return value
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }

    private static string FormatOptionalStringArgument(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : $", \"{EscapeString(value)}\"";
    }

    private static string FormatOptionalFilterCommitMode(FilterPopupCommitMode? value)
    {
        return value is null or FilterPopupCommitMode.Apply
            ? string.Empty
            : $", FilterPopupCommitMode.{value.Value}";
    }

    private static string FormatOptionalFolderExportCommitMode(FolderExportCommitMode? value)
    {
        return value is null or FolderExportCommitMode.Select
            ? string.Empty
            : $", FolderExportCommitMode.{value.Value}";
    }

    private static string FormatOptionalGridCellEditCommitMode(GridCellEditCommitMode? value)
    {
        return value is null or GridCellEditCommitMode.Commit
            ? string.Empty
            : $", GridCellEditCommitMode.{value.Value}";
    }

    private static bool HasNamedGridRow(RecordedStep step)
    {
        return step.GridRowConditions is { Count: > 0 };
    }

    private static string FormatGridRowSelector(RecordedStep step)
    {
        var conditions = step.GridRowConditions
            ?? throw new InvalidOperationException("Named grid step does not contain row conditions.");
        if (conditions.Count == 0)
        {
            throw new InvalidOperationException("Named grid step does not contain row conditions.");
        }

        var builder = new StringBuilder();
        var first = conditions[0];
        builder.Append("GridRowSelector.ByCell(\"")
            .Append(EscapeString(first.ColumnName))
            .Append("\", \"")
            .Append(EscapeString(first.Value))
            .Append("\")");
        for (var index = 1; index < conditions.Count; index++)
        {
            var condition = conditions[index];
            builder.Append(".AndCell(\"")
                .Append(EscapeString(condition.ColumnName))
                .Append("\", \"")
                .Append(EscapeString(condition.Value))
                .Append("\")");
        }

        return builder.ToString();
    }

    private static string FormatGridTargetColumn(RecordedStep step)
    {
        return $"\"{EscapeString(step.GridTargetColumnName ?? string.Empty)}\"";
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
    }

    private static string FormatStringValues(IReadOnlyList<string>? values)
    {
        var renderedValues = values?
            .Select(static value => value?.Trim() ?? string.Empty)
            .OrderBy(static value => value, StringComparer.Ordinal)
            .Select(static value => $"\"{EscapeString(value)}\"")
            .ToArray() ?? [];
        if (renderedValues.Length == 0)
        {
            return "global::System.Array.Empty<string>()";
        }

        return $"new[] {{ {string.Join(", ", renderedValues)} }}";
    }

    private static string FormatOrderedStringValues(IReadOnlyList<string>? values)
    {
        var renderedValues = values?
            .Select(static value => $"\"{EscapeString(value ?? string.Empty)}\"")
            .ToArray() ?? [];
        return renderedValues.Length == 0
            ? "global::System.Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", renderedValues)} }}";
    }

    private static string FormatBoolean(bool? value)
    {
        return value == true ? "true" : "false";
    }

    private static string FormatDouble(double? value)
    {
        return (value ?? 0).ToString("G17", CultureInfo.InvariantCulture);
    }

    private static string FormatNullableDouble(double? value)
    {
        return value.HasValue
            ? FormatDouble(value)
            : "null";
    }

    private static string FormatInt(int? value)
    {
        return (value ?? 0).ToString(CultureInfo.InvariantCulture);
    }

    private static bool HasRelativeDateExpression(RecordedStep step)
    {
        return step.DateExpression?.ReferenceKind == RecorderDateReferenceKind.RelativeToToday
            || step.SecondDateExpression?.ReferenceKind == RecorderDateReferenceKind.RelativeToToday;
    }

    private static string FormatDate(DateTime? value, RecorderDateExpression? expression = null)
    {
        if (expression?.ReferenceKind == RecorderDateReferenceKind.RelativeToToday)
        {
            return expression.DayOffset == 0
                ? "DateTime.Today"
                : $"DateTime.Today.AddDays({expression.DayOffset.ToString(CultureInfo.InvariantCulture)})";
        }

        if (expression is not null && expression.ReferenceKind != RecorderDateReferenceKind.Exact)
        {
            throw new InvalidOperationException(
                $"Date reference kind '{expression.ReferenceKind}' is not supported.");
        }

        var date = (value ?? DateTime.Today).Date;
        return $"new global::System.DateTime({date.Year}, {date.Month}, {date.Day})";
    }

    private static string FormatTimeSpan(TimeSpan? value)
    {
        return value.HasValue
            ? $"new global::System.TimeSpan({value.Value.Ticks}L)"
            : "default";
    }

    private static string FormatNullableTimeSpan(TimeSpan? value)
    {
        return value.HasValue
            ? FormatTimeSpan(value)
            : "null";
    }

    private static string FormatNullableDate(
        DateTime? value,
        RecorderDateExpression? expression = null)
    {
        return value.HasValue
            ? FormatDate(value, expression)
            : "null";
    }
}

internal enum AuthoringSaveKind
{
    Snapshot = 0,
    Autosave = 1
}

internal sealed record AuthoringSaveTarget(
    string PageFilePath,
    string ScenarioFilePath,
    string MethodName);

internal sealed record AutosaveTargetRegistration(
    string DestinationKey,
    AuthoringSaveTarget Target);
